import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './HomePage/Navbar'
import AppState from './store/AppContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <AppState> */}
        <Navbar />
        {children}
        {/* </AppState> */}
      </body>
    </html>
  )
}
